import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../share/styles/index.module.scss'
import SystemPopup from '../components/system/system'
import AboutPopup from '../components/about/about'
import BinPopup from '../components/bin/bin'
import PortfolioPopup from '../components/portfolio/portfolio'
import ServicesPopup from '../components/services/services'
import { GetStaticPropsContext } from 'next';

const inter = Inter({ subsets: ['latin'] })


export default function Home(isActive: boolean) {

  return (
    <>
      <Head>
        <title>UndercoverADV | Your Partner In Crime Since 2008</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} f-column j-between a-center`}>

        <SystemPopup />
        <AboutPopup />
        <BinPopup />
        <PortfolioPopup />
        <ServicesPopup />
      </main>
    </>
  )
}

// Internationalization
export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`../share/lang/${locale}.json`)).default
    }
  }
}