import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../share/styles/index.module.scss'
import PopupTopbar from '../share/ui/popup-topbar/popupTopbar'
import { GenericPopup } from '../share/ui/generic-popup/genericPopup'
import SystemPopup from '../components/system/system'

const inter = Inter({ subsets: ['latin'] })


export default function Home(isActive: boolean) {
  isActive = false
  return (
    <>
      <Head>
        <title>UndercoverADV | Your Partner In Crime Since 2008</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} f-column j-between a-center`}>
        <GenericPopup id='popup' hasScroll={false} hasSidebar={false} />
        <SystemPopup />
      </main>
    </>
  )
}
