import Head from 'next/head'
import styles from '../share/styles/index.module.scss'
import { GetStaticPropsContext } from 'next';
import Desktop from '../components/desktop/desktop';



export default function Home(isActive: boolean) {

  return (
    <>
      <Head>
        <title>UndercoverADV | Your Partner In Crime Since 2008</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} f-column j-between a-center`}>
        <Desktop />
      </main>
    </>
  )
}

// Internationalization
export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      messages: (await import(`../share/lang/${locale}.json`)).default
    }
  }
}